FROM ubuntu:20.04
RUN apt update
RUN apt install binutils build-essential golang sysstat python3-matplotlib python3-pil fonts-takao fio libvirt-clients virtinst jq docker.io containerd libvirt-daemon-system
WORKDIR /linux-study
